Revert arm64: sigcontext: use standard __uint128_t type for vregs in… … struct fpsimd_context."
This reverts commit 447dabc1fedbafb1f9894e0c3054bf546a1af913
as it causes this issue with the Android build system:

out/soong/.intermediates/vendor/lineage/build/soong/generated_kernel_includes/ge
n/usr/include/asm/sigcontext.h:53:2: error: unknown type name '__uint128_t'
        __uint128_t vregs[32];
Signed-off-by: YadavMohit19 <mohityadav050575@gmail.com>